/**
 * SmartCare Database Types
 *
 * This file will eventually be auto-generated by the Supabase CLI:
 *   npx supabase gen types typescript --project-id <project-id> > src/types/database.ts
 *
 * For now it is hand-written to match the Phase 1 foundation schema.
 * Update this file after each migration is applied.
 *
 * ─── Naming conventions ─────────────────────────────────────────
 *   Row       → the shape returned by SELECT
 *   Insert    → the shape required for INSERT (id/timestamps optional)
 *   Update    → Partial<Insert> (all fields optional for UPDATE)
 */

// ─────────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────────

export type UserRole = "patient" | "doctor" | "admin";

export type BloodType =
  | "A+"
  | "A-"
  | "B+"
  | "B-"
  | "AB+"
  | "AB-"
  | "O+"
  | "O-";

export type Gender =
  | "male"
  | "female"
  | "other"
  | "prefer_not_to_say";

export type RelationshipStatus =
  | "pending"
  | "active"
  | "inactive"
  | "revoked";

export type InitiatorRole = "doctor" | "patient";

// ─────────────────────────────────────────────────────────────────────────────
// Table: profiles
// ─────────────────────────────────────────────────────────────────────────────

export interface ProfileRow {
  id: string; // UUID — matches auth.users.id
  role: UserRole;
  full_name: string;
  avatar_url: string | null;
  phone: string | null;
  date_of_birth: string | null; // ISO 8601 date string
  gender: Gender | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ProfileInsert {
  id: string;
  role?: UserRole;
  full_name: string;
  avatar_url?: string | null;
  phone?: string | null;
  date_of_birth?: string | null;
  gender?: Gender | null;
  is_active?: boolean;
}

export type ProfileUpdate = Partial<Omit<ProfileInsert, "id">>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: patient_profiles
// ─────────────────────────────────────────────────────────────────────────────

export interface PatientProfileRow {
  id: string;
  profile_id: string;
  blood_type: BloodType | null;
  allergies: string[];
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  insurance_provider: string | null;
  insurance_policy_number: string | null;
  created_at: string;
  updated_at: string;
}

export interface PatientProfileInsert {
  profile_id: string;
  blood_type?: BloodType | null;
  allergies?: string[];
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  insurance_provider?: string | null;
  insurance_policy_number?: string | null;
}

export type PatientProfileUpdate = Partial<Omit<PatientProfileInsert, "profile_id">>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: doctor_profiles
// ─────────────────────────────────────────────────────────────────────────────

export interface DoctorProfileRow {
  id: string;
  profile_id: string;
  license_number: string;
  specialty: string;
  department: string | null;
  years_of_experience: number | null;
  bio: string | null;
  is_verified: boolean;
  verified_by: string | null;
  verified_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface DoctorProfileInsert {
  profile_id: string;
  license_number: string;
  specialty: string;
  department?: string | null;
  years_of_experience?: number | null;
  bio?: string | null;
  is_verified?: boolean;
  verified_by?: string | null;
  verified_at?: string | null;
}

export type DoctorProfileUpdate = Partial<Omit<DoctorProfileInsert, "profile_id">>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: doctor_patient_relationships
// ─────────────────────────────────────────────────────────────────────────────

export interface DoctorPatientRelationshipRow {
  id: string;
  doctor_id: string;
  patient_id: string;
  status: RelationshipStatus;
  initiated_by: string;
  initiator_role: InitiatorRole;
  established_at: string | null;
  revoked_at: string | null;
  revoked_by: string | null;
  notes: string | null;
  created_at?: string; // implied by conventions
}

export interface DoctorPatientRelationshipInsert {
  doctor_id: string;
  patient_id: string;
  status?: RelationshipStatus;
  initiated_by: string;
  initiator_role: InitiatorRole;
  notes?: string | null;
}

export type DoctorPatientRelationshipUpdate = Partial<
  Pick<DoctorPatientRelationshipRow, "status" | "established_at" | "revoked_at" | "revoked_by" | "notes">
>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: audit_logs
// ─────────────────────────────────────────────────────────────────────────────

export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  old_values: Record<string, unknown> | null;
  new_values: Record<string, unknown> | null;
  metadata: Record<string, unknown> | null;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

export interface AuditLogInsert {
  actor_id?: string | null;
  action: string;
  resource_type: string;
  resource_id?: string | null;
  old_values?: Record<string, unknown> | null;
  new_values?: Record<string, unknown> | null;
  metadata?: Record<string, unknown> | null;
  ip_address?: string | null;
  user_agent?: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Supabase Database shape (used as the generic type parameter for createClient)
// ─────────────────────────────────────────────────────────────────────────────

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
      };
      patient_profiles: {
        Row: PatientProfileRow;
        Insert: PatientProfileInsert;
        Update: PatientProfileUpdate;
      };
      doctor_profiles: {
        Row: DoctorProfileRow;
        Insert: DoctorProfileInsert;
        Update: DoctorProfileUpdate;
      };
      doctor_patient_relationships: {
        Row: DoctorPatientRelationshipRow;
        Insert: DoctorPatientRelationshipInsert;
        Update: DoctorPatientRelationshipUpdate;
      };
      audit_logs: {
        Row: AuditLogRow;
        Insert: AuditLogInsert;
        Update: never; // audit logs are append-only
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
    };
    Enums: {
      user_role: UserRole;
      blood_type: BloodType;
      gender: Gender;
      relationship_status: RelationshipStatus;
      initiator_role: InitiatorRole;
    };
  };
}
