/**
 * SmartCare Database Types
 *
 * This file will eventually be auto-generated by the Supabase CLI:
 *   npx supabase gen types typescript --project-id <project-id> \
 *     --schema public > src/types/database.ts
 *
 * For now it is hand-written to match the Phase 1 Step 2 foundation schema
 * (migrations 001–003). Update this file after each migration is applied.
 *
 * ─── Naming conventions ───────────────────────────────────────────────────
 *   Row    → shape returned by SELECT
 *   Insert → shape required for INSERT (id/timestamps optional where defaulted)
 *   Update → Partial<Omit<Insert, immutable_fields>>
 *
 * ─── Changes in Phase 1 Step 2 ───────────────────────────────────────────
 *   - Renamed: doctor_profiles → doctors (matches real table name)
 *   - Fixed:   initiated_by is nullable (ON DELETE SET NULL on FK)
 *   - Removed: patient_profiles and audit_logs from Database.Tables
 *              (deferred — Phase 3). TypeScript types kept as placeholders
 *              for future use but not wired into the Database generic yet.
 *   - Added:   get_user_role and has_active_relationship to Functions
 */

// ─────────────────────────────────────────────────────────────────────────────
// Enums  (mirror PostgreSQL native enums created in 001_foundation_schema.sql)
// ─────────────────────────────────────────────────────────────────────────────

export type UserRole = "patient" | "doctor" | "admin";

export type Gender =
  | "male"
  | "female"
  | "other"
  | "prefer_not_to_say";

export type RelationshipStatus =
  | "pending"
  | "active"
  | "inactive"
  | "revoked"
  | "rejected";

export type InitiatorRole = "doctor" | "patient";

/**
 * Record types for medical records (Phase 2 Step 3)
 */
export type RecordType = "clinical_note" | "lab_result" | "prescription" | "imaging" | "other";

/**
 * Appointment status (Phase 3 Step 1)
 */
export type AppointmentStatus = "pending" | "confirmed" | "completed" | "cancelled" | "rejected";

/**
 * Prescription status (Phase 3 Step 2)
 */
export type PrescriptionStatus = "active" | "completed" | "discontinued";

/**
 * Admin Verification Status (Phase 7)
 */
export type DoctorVerificationStatus = "pending" | "approved" | "rejected";

// Deferred with patient_profiles (Phase 3) — kept here for future use
export type BloodType =
  | "A+"
  | "A-"
  | "B+"
  | "B-"
  | "AB+"
  | "AB-"
  | "O+"
  | "O-";

// ─────────────────────────────────────────────────────────────────────────────
// Table: profiles
// ─────────────────────────────────────────────────────────────────────────────

export interface ProfileRow {
  /** UUID — equals auth.users.id (1:1) */
  id: string;
  role: UserRole;
  full_name: string;
  avatar_url: string | null;
  phone: string | null;
  /** ISO 8601 date string (e.g. "1990-06-15") */
  date_of_birth: string | null;
  gender: Gender | null;
  is_active: boolean;
  notification_preferences: { email: boolean; in_app: boolean };
  created_at: string;
  updated_at: string;
}

export interface ProfileInsert {
  /** Must equal the auth.users.id — assigned by Supabase Auth, not generated */
  id: string;
  role?: UserRole;
  full_name: string;
  avatar_url?: string | null;
  phone?: string | null;
  date_of_birth?: string | null;
  gender?: Gender | null;
  is_active?: boolean;
  notification_preferences?: { email: boolean; in_app: boolean };
}

/** Supabase strictly typed Update requires Partial of the Row */
export type ProfileUpdate = Partial<ProfileRow>;
// role is excluded: role changes require the admin service-role client

// ─────────────────────────────────────────────────────────────────────────────
// Table: doctors  (was "doctor_profiles" — renamed to match real table)
// ─────────────────────────────────────────────────────────────────────────────

export interface DoctorRow {
  /** Generated UUID */
  id: string;
  /** FK → profiles(id) — the doctor's profile */
  profile_id: string;
  license_number: string;
  specialty: string;
  department: string | null;
  years_of_experience: number | null;
  bio: string | null;
  is_accepting_appointments: boolean;
  appointment_duration: number;
  clinic_name: string | null;
  clinic_address: string | null;
  /** Only admin can set this to true */
  is_verified: boolean;
  verification_status: DoctorVerificationStatus;
  rejection_reason: string | null;
  rejected_at: string | null;
  rejected_by: string | null;
  /** FK → profiles(id) — the admin who verified; null if admin deleted */
  verified_by: string | null;
  verified_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface DoctorInsert {
  profile_id: string;
  license_number: string;
  specialty: string;
  department?: string | null;
  years_of_experience?: number | null;
  bio?: string | null;
  is_accepting_appointments?: boolean;
  appointment_duration?: number;
  clinic_name?: string | null;
  clinic_address?: string | null;
  is_verified?: boolean;
  verification_status?: DoctorVerificationStatus;
  rejection_reason?: string | null;
  rejected_at?: string | null;
  rejected_by?: string | null;
  verified_by?: string | null;
  verified_at?: string | null;
}

/** Supabase strictly typed Update requires Partial of the Row */
export type DoctorUpdate = Partial<DoctorRow>;

/** Admin-only update shape — used with service-role client */
export type DoctorAdminUpdate = Partial<
  Omit<DoctorInsert, "profile_id" | "license_number">
>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: doctor_patient_relationships
// ─────────────────────────────────────────────────────────────────────────────

export interface DoctorPatientRelationshipRow {
  /** Generated UUID */
  id: string;
  /** FK → profiles(id); role must be 'doctor' */
  doctor_id: string;
  /** FK → profiles(id); role must be 'patient' */
  patient_id: string;
  status: RelationshipStatus;
  /** FK → profiles(id); nullable — SET NULL if initiator's profile is deleted */
  initiated_by: string | null;
  initiator_role: InitiatorRole;
  /** Set by trigger when status transitions TO 'active' */
  established_at: string | null;
  /** Set by trigger when status transitions TO 'revoked' */
  revoked_at: string | null;
  /** FK → profiles(id); nullable */
  revoked_by: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface DoctorPatientRelationshipInsert {
  doctor_id: string;
  patient_id: string;
  /** Always 'pending' on insert — enforced by RLS WITH CHECK */
  status?: "pending";
  initiated_by: string;
  initiator_role: InitiatorRole;
  notes?: string | null;
}

/** Supabase strictly typed Update requires Partial of the Row */
export type DoctorPatientRelationshipUpdate = Partial<DoctorPatientRelationshipRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: medical_records (Phase 2 Step 3)
// ─────────────────────────────────────────────────────────────────────────────

export interface MedicalRecordRow {
  id: string;
  patient_id: string;
  doctor_id: string | null;
  title: string;
  description: string | null;
  type: RecordType;
  attachment_url: string | null;
  record_date: string;
  created_at: string;
  updated_at: string;
}

export type MedicalRecordInsert = Omit<MedicalRecordRow, "id" | "created_at" | "updated_at"> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

export type MedicalRecordUpdate = Partial<MedicalRecordRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: appointments (Phase 3 Step 1)
// ─────────────────────────────────────────────────────────────────────────────

export interface AppointmentRow {
  id: string;
  patient_id: string;
  doctor_id: string;
  appointment_date: string;
  appointment_time: string;
  reason: string;
  status: AppointmentStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export type AppointmentInsert = Omit<AppointmentRow, "id" | "status" | "created_at" | "updated_at"> & {
  id?: string;
  status?: AppointmentStatus;
  created_at?: string;
  updated_at?: string;
};

export type AppointmentUpdate = Partial<AppointmentRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: prescriptions (Phase 3 Step 2)
// ─────────────────────────────────────────────────────────────────────────────

export interface PrescriptionRow {
  id: string;
  patient_id: string;
  doctor_id: string;
  medication_name: string;
  dosage: string;
  frequency: string;
  start_date: string;
  end_date: string | null;
  status: PrescriptionStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export type PrescriptionInsert = Omit<PrescriptionRow, "id" | "status" | "created_at" | "updated_at"> & {
  id?: string;
  status?: PrescriptionStatus;
  created_at?: string;
  updated_at?: string;
};

export type PrescriptionUpdate = Partial<PrescriptionRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: consultation_notes (Phase 3 Step 3)
// ─────────────────────────────────────────────────────────────────────────────

export interface ConsultationNoteRow {
  id: string;
  appointment_id: string;
  patient_id: string;
  doctor_id: string;
  diagnosis: string;
  symptoms: string;
  observations: string;
  treatment_plan: string;
  follow_up_date: string | null;
  created_at: string;
  updated_at: string;
}

export type ConsultationNoteInsert = Omit<ConsultationNoteRow, "id" | "created_at" | "updated_at"> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

export type ConsultationNoteUpdate = Partial<ConsultationNoteRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Deferred placeholder types  (patient_profiles, audit_logs — Phase 3)
// Not wired into the Database generic yet.
// ─────────────────────────────────────────────────────────────────────────────

/** @deferred Phase 3 — patient_profiles table */
export interface PatientProfileRow {
  id: string;
  profile_id: string;
  blood_type: BloodType | null;
  allergies: string[];
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  insurance_provider: string | null;
  insurance_policy_number: string | null;
  created_at: string;
  updated_at: string;
}

/** @deferred Phase 3 — audit_logs table */
export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  old_values: Record<string, unknown> | null;
  new_values: Record<string, unknown> | null;
  metadata: Record<string, unknown> | null;
  ip_address: string | null;
  user_agent: string | null;
  created_at: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Table: doctor_availability (Phase 3/4)
// ─────────────────────────────────────────────────────────────────────────────

export interface DoctorAvailabilityRow {
  id: string;
  doctor_id: string;
  day_of_week: number;
  start_time: string;
  end_time: string;
  break_start_time: string | null;
  break_end_time: string | null;
  created_at: string;
  updated_at: string;
}

export type DoctorAvailabilityInsert = Omit<DoctorAvailabilityRow, "id" | "created_at" | "updated_at"> & {
  id?: string;
  created_at?: string;
  updated_at?: string;
};

export type DoctorAvailabilityUpdate = Partial<DoctorAvailabilityRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Table: notifications (Phase 3/4)
// ─────────────────────────────────────────────────────────────────────────────

export type NotificationType = 
  | "relationship_request_received"
  | "relationship_request_accepted"
  | "relationship_request_rejected"
  | "appointment_requested"
  | "appointment_confirmed"
  | "appointment_cancelled"
  | "appointment_rejected"
  | "prescription_created"
  | "consultation_note_added";

export interface NotificationRow {
  id: string;
  user_id: string;
  title: string;
  message: string;
  type: NotificationType;
  related_entity_id: string | null;
  is_read: boolean;
  created_at: string;
  updated_at: string;
}

export type NotificationInsert = Omit<NotificationRow, "id" | "is_read" | "created_at" | "updated_at"> & {
  id?: string;
  is_read?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type NotificationUpdate = Partial<NotificationRow>;

// ─────────────────────────────────────────────────────────────────────────────
// Database — generic type for createClient<Database>(...)
// Reflects only the tables that exist in the current schema (Phase 1 Step 2).
// ─────────────────────────────────────────────────────────────────────────────

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: unknown[];
      };
      doctors: {
        Row: DoctorRow;
        Insert: DoctorInsert;
        Update: DoctorUpdate;
        Relationships: unknown[];
      };
      doctor_patient_relationships: {
        Row: DoctorPatientRelationshipRow;
        Insert: DoctorPatientRelationshipInsert;
        Update: DoctorPatientRelationshipUpdate;
        Relationships: unknown[];
      };
      medical_records: {
        Row: MedicalRecordRow;
        Insert: MedicalRecordInsert;
        Update: MedicalRecordUpdate;
        Relationships: [
          {
            foreignKeyName: "medical_records_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "medical_records_doctor_id_fkey";
            columns: ["doctor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      appointments: {
        Row: AppointmentRow;
        Insert: AppointmentInsert;
        Update: AppointmentUpdate;
        Relationships: [
          {
            foreignKeyName: "appointments_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "appointments_doctor_id_fkey";
            columns: ["doctor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      prescriptions: {
        Row: PrescriptionRow;
        Insert: PrescriptionInsert;
        Update: PrescriptionUpdate;
        Relationships: [
          {
            foreignKeyName: "prescriptions_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "prescriptions_doctor_id_fkey";
            columns: ["doctor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      consultation_notes: {
        Row: ConsultationNoteRow;
        Insert: ConsultationNoteInsert;
        Update: ConsultationNoteUpdate;
        Relationships: [
          {
            foreignKeyName: "consultation_notes_appointment_id_fkey";
            columns: ["appointment_id"];
            isOneToOne: true;
            referencedRelation: "appointments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "consultation_notes_patient_id_fkey";
            columns: ["patient_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "consultation_notes_doctor_id_fkey";
            columns: ["doctor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_user_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
      has_active_relationship: {
        Args: { p_doctor_id: string; p_patient_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: UserRole;
      gender: Gender;
      relationship_status: RelationshipStatus;
      initiator_role: InitiatorRole;
      appointment_status: AppointmentStatus;
      prescription_status: PrescriptionStatus;
    };
  };
}
